artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://www.kaggle.com/datasets/warcoder/indian-medicinal-leaf-image-dataset/data
  # local_data_file : artifacts/data_ingestion/Med_leaf.zip
  unzip_dir : artifacts/data_ingestion
